### ISSUE TITLE
Why would the snakecase package be in src/ and not in vendor/?

### ISSUE THREAD

**Issue by pengux** [fatih/gb-example#1]
As the full import path is github.com/fatih/snakecase, it can also be classified as third party package so it seems more logical to put it in the vendor/ folder.

**Comment by fatih** [comment]
It's an internal package, it's not `github.com/fatih/snakecase`, is under `github.com/fatih/gb-example/snakecase`. It's not something that can be imported by others or can be used by any other third party package.
